import React, { useState, useEffect } from 'react';
import { 
  Shield, 
  Download, 
  Check, 
  Copy, 
  X, 
  Activity, 
  Terminal, 
  Globe, 
  Radio, 
  AlertCircle, 
  ArrowRight,
  RefreshCw,
  Server
} from 'lucide-react';
import { useApp } from '../../context/AppContext';

interface TryHackMeOpenVpnModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const TryHackMeOpenVpnModal: React.FC<TryHackMeOpenVpnModalProps> = ({ isOpen, onClose }) => {
  const { profile, currentUser } = useApp();
  const [selectedRegion, setSelectedRegion] = useState<'ap-south' | 'eu-west' | 'us-east'>('ap-south');
  const [isCopied, setIsCopied] = useState(false);
  const [isPinging, setIsPinging] = useState(false);
  const [pingStatus, setPingStatus] = useState<'idle' | 'success' | 'failed'>('idle');
  const [assignedIp, setAssignedIp] = useState('10.8.44.12');

  const username = profile?.name ? profile.name.toLowerCase().replace(/\s+/g, '_') : (currentUser?.displayName ? currentUser.displayName.toLowerCase().replace(/\s+/g, '_') : 'operator');

  if (!isOpen) return null;

  const handleCopyCommand = () => {
    navigator.clipboard.writeText(`sudo openvpn mycyberlab-${username}-${selectedRegion}.ovpn`);
    setIsCopied(true);
    setTimeout(() => setIsCopied(false), 2000);
  };

  const handleDownloadOvpn = () => {
    const ovpnContent = `client
dev tun
proto udp
remote vpn-${selectedRegion}.mycyberlab.academy 1194
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
auth SHA256
cipher AES-256-GCM
key-direction 1
verb 3
# User: ${username}
# Assigned VIP Gateway: 10.8.0.0/16 Subnet
# Generated by MY CYBER LAB OpenVPN Authority
<ca>
-----BEGIN CERTIFICATE-----
MIIDQjCCAi6gAwIBAgIUe9z8Fz5...[MYCYBERLAB_ROOT_CA_CERT]...
-----END CERTIFICATE-----
</ca>
<cert>
-----BEGIN CERTIFICATE-----
MIIDPzCCAiegAwIBAgIBATANBgk...[CLIENT_CERT_${username.toUpperCase()}]...
-----END CERTIFICATE-----
</cert>
<key>
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQE...[CLIENT_PRIVATE_KEY]...
-----END PRIVATE KEY-----
</key>
<tls-auth>
# 2048 bit OpenVPN static key
-----BEGIN OpenVPN Static key V1-----
a1b2c3d4e5f6...[TLS_AUTH_KEY]...
-----END OpenVPN Static key V1-----
</tls-auth>`;

    const blob = new Blob([ovpnContent], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `mycyberlab-${username}-${selectedRegion}.ovpn`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handleTestTunnel = () => {
    setIsPinging(true);
    setPingStatus('idle');
    setTimeout(() => {
      setIsPinging(false);
      setPingStatus('success');
    }, 1200);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/85 backdrop-blur-md animate-fadeIn">
      <div className="bg-slate-900 border border-cyan-500/40 rounded-2xl w-full max-w-2xl overflow-hidden shadow-2xl relative">
        
        {/* Modal Header */}
        <div className="bg-slate-950 px-6 py-4 border-b border-slate-800 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-cyan-950/80 border border-cyan-500/40 flex items-center justify-center text-cyan-400">
              <Shield className="w-5 h-5" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="font-mono font-bold text-sm text-slate-100">
                  MYCYBERLAB ACCESS CONTROL & OPENVPN
                </h3>
                <span className="px-2 py-0.5 rounded text-[10px] font-mono bg-emerald-950 text-emerald-300 border border-emerald-500/30">
                  TUNNEL ACTIVE
                </span>
              </div>
              <p className="text-xs text-slate-400">Direct layer-2 encrypted routing to TryHackMe-style target subnets (10.10.0.0/16)</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="text-slate-400 hover:text-slate-200 p-1.5 rounded-lg hover:bg-slate-800 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Modal Body */}
        <div className="p-6 space-y-6 max-h-[75vh] overflow-y-auto custom-scrollbar">
          
          {/* Status & Assigned VPN IP */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
            <div className="bg-slate-950 p-3.5 rounded-xl border border-slate-800">
              <div className="text-[10px] font-mono text-slate-400 uppercase tracking-wider mb-1 flex items-center gap-1.5">
                <Activity className="w-3.5 h-3.5 text-cyan-400" />
                Assigned Tunnel IP
              </div>
              <div className="font-mono text-sm font-bold text-cyan-300">{assignedIp}</div>
              <div className="text-[10px] text-slate-500 mt-0.5">Interface: tun0</div>
            </div>

            <div className="bg-slate-950 p-3.5 rounded-xl border border-slate-800">
              <div className="text-[10px] font-mono text-slate-400 uppercase tracking-wider mb-1 flex items-center gap-1.5">
                <Globe className="w-3.5 h-3.5 text-emerald-400" />
                Target Cyber Range Subnet
              </div>
              <div className="font-mono text-sm font-bold text-emerald-300">10.10.0.0/16</div>
              <div className="text-[10px] text-slate-500 mt-0.5">Direct Route Active</div>
            </div>

            <div className="bg-slate-950 p-3.5 rounded-xl border border-slate-800">
              <div className="text-[10px] font-mono text-slate-400 uppercase tracking-wider mb-1 flex items-center gap-1.5">
                <Server className="w-3.5 h-3.5 text-purple-400" />
                Gateway Server
              </div>
              <div className="font-mono text-sm font-bold text-purple-300">
                {selectedRegion === 'ap-south' ? 'India / AP-South' : selectedRegion === 'eu-west' ? 'EU-West (Frankfurt)' : 'US-East (N. Virginia)'}
              </div>
              <div className="text-[10px] text-slate-500 mt-0.5">Latency: ~18ms</div>
            </div>
          </div>

          {/* Region Selector */}
          <div>
            <label className="text-xs font-mono font-bold text-slate-300 uppercase tracking-wider block mb-2">
              Select VPN Gateway Region
            </label>
            <div className="grid grid-cols-3 gap-3">
              {[
                { id: 'ap-south', name: 'AP-South (India / Mumbai)', ping: '18ms' },
                { id: 'eu-west', name: 'EU-West (Frankfurt)', ping: '110ms' },
                { id: 'us-east', name: 'US-East (Virginia)', ping: '170ms' },
              ].map(reg => (
                <button
                  key={reg.id}
                  onClick={() => setSelectedRegion(reg.id as any)}
                  className={`p-3 rounded-xl border text-left transition-all cursor-pointer ${
                    selectedRegion === reg.id
                      ? 'bg-cyan-950/60 border-cyan-400 text-slate-100 ring-1 ring-cyan-500/40'
                      : 'bg-slate-950/60 border-slate-800 text-slate-400 hover:bg-slate-900 hover:border-slate-700'
                  }`}
                >
                  <div className="font-mono font-bold text-xs">{reg.name}</div>
                  <div className="text-[10px] font-mono text-emerald-400 mt-1">● {reg.ping}</div>
                </button>
              ))}
            </div>
          </div>

          {/* Download & Command instructions */}
          <div className="bg-slate-950 rounded-xl border border-slate-800 p-4 space-y-3">
            <div className="flex items-center justify-between">
              <div className="text-xs font-mono font-bold text-slate-200 flex items-center gap-2">
                <Terminal className="w-4 h-4 text-cyan-400" />
                Step 1: Download Configuration File
              </div>
              <button
                onClick={handleDownloadOvpn}
                className="px-3.5 py-1.5 rounded-lg bg-cyan-500 hover:bg-cyan-400 text-slate-950 font-mono font-bold text-xs transition-all flex items-center gap-1.5 cursor-pointer shadow-md shadow-cyan-500/20"
              >
                <Download className="w-3.5 h-3.5" />
                Download .ovpn
              </button>
            </div>
            
            <div className="pt-2 border-t border-slate-800/80">
              <div className="text-xs font-mono font-bold text-slate-200 mb-1.5">
                Step 2: Connect from Kali Linux or Terminal
              </div>
              <div className="flex items-center justify-between bg-slate-900 border border-slate-800 rounded-lg p-2.5 font-mono text-xs text-cyan-300">
                <span>sudo openvpn mycyberlab-{username}-{selectedRegion}.ovpn</span>
                <button
                  onClick={handleCopyCommand}
                  className="text-slate-400 hover:text-cyan-400 transition-colors p-1"
                  title="Copy command"
                >
                  {isCopied ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
                </button>
              </div>
            </div>
          </div>

          {/* Tunnel Diagnostics & Heartbeat Test */}
          <div className="bg-slate-950/70 border border-slate-800 rounded-xl p-3.5 flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="w-8 h-8 rounded-lg bg-cyan-950/80 border border-cyan-500/40 flex items-center justify-center text-cyan-400">
                <Activity className="w-4 h-4" />
              </div>
              <div>
                <div className="text-xs font-bold text-slate-200 font-mono">Tunnel Heartbeat & Routing Diagnostic</div>
                <div className="text-[11px] text-slate-400">Ping range gateway 10.10.10.1 to verify packet forwarding</div>
              </div>
            </div>
            <button
              onClick={handleTestTunnel}
              disabled={isPinging}
              className="px-3.5 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 border border-slate-700 text-xs font-mono font-bold text-slate-200 transition-all flex items-center gap-1.5 cursor-pointer disabled:opacity-50"
            >
              <RefreshCw className={`w-3.5 h-3.5 ${isPinging ? 'animate-spin text-cyan-400' : ''}`} />
              {isPinging ? 'Pinging Gateway...' : pingStatus === 'success' ? 'Connected (0% Loss)' : 'Test Tunnel'}
            </button>
          </div>

        </div>

        {/* Modal Footer */}
        <div className="bg-slate-950 px-6 py-3.5 border-t border-slate-800 flex items-center justify-between">
          <div className="text-xs font-mono text-slate-400 flex items-center gap-1.5">
            <span className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse" />
            Prefer in-browser? Use our built-in <strong className="text-cyan-400">AttackBox Web Terminal</strong>.
          </div>
          <button
            onClick={onClose}
            className="px-4 py-2 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-200 font-mono font-bold text-xs transition-colors cursor-pointer"
          >
            Done
          </button>
        </div>

      </div>
    </div>
  );
};
